// Generated by the protocol buffer compiler.  DO NOT EDIT!

package cn.yachaozz.netty.netty.proto;

@SuppressWarnings("hiding")
public interface MyDateInfo {

  public static final class MyMessage extends
      com.google.protobuf.nano.MessageNano {

    // enum DateType
    public static final int StudentType = 0;
    public static final int WorkerType = 1;
    public static final int STUDENT_FIELD_NUMBER = 2;
    public static final int WORKER_FIELD_NUMBER = 3;
    private int dataBodyCase_ = 0;
    private Object dataBody_;
    public int getDataBodyCase() {
      return this.dataBodyCase_;
    }
    public MyMessage clearDataBody() {
      this.dataBodyCase_ = 0;
      this.dataBody_ = null;
      return this;
    }

    private static volatile MyMessage[] _emptyArray;
    public static MyMessage[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new MyMessage[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .MyMessage.DateType date_type = 1;
    public int dateType;

    // optional .Student student = 2;
    public boolean hasStudent() {
      return this.dataBodyCase_ == 2;
    }
    public MyDateInfo.Student getStudent() {
      if (this.dataBodyCase_ == 2) {
        return (MyDateInfo.Student) this.dataBody_;
      }
      return null;
    }
    public MyMessage setStudent(MyDateInfo.Student value) {
      if (value == null) { throw new NullPointerException(); }
      this.dataBodyCase_ = 2;
      this.dataBody_ = value;
      return this;
    }

    // optional .Worker worker = 3;
    public boolean hasWorker() {
      return this.dataBodyCase_ == 3;
    }
    public MyDateInfo.Worker getWorker() {
      if (this.dataBodyCase_ == 3) {
        return (MyDateInfo.Worker) this.dataBody_;
      }
      return null;
    }
    public MyMessage setWorker(MyDateInfo.Worker value) {
      if (value == null) { throw new NullPointerException(); }
      this.dataBodyCase_ = 3;
      this.dataBody_ = value;
      return this;
    }

    public MyMessage() {
      clear();
    }

    public MyMessage clear() {
      dateType = MyDateInfo.MyMessage.StudentType;
      clearDataBody();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.dateType != MyDateInfo.MyMessage.StudentType) {
        output.writeInt32(1, this.dateType);
      }
      if (this.dataBodyCase_ == 2) {
        output.writeMessage(2,
            (com.google.protobuf.nano.MessageNano) this.dataBody_);
      }
      if (this.dataBodyCase_ == 3) {
        output.writeMessage(3,
            (com.google.protobuf.nano.MessageNano) this.dataBody_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.dateType != MyDateInfo.MyMessage.StudentType) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.dateType);
      }
      if (this.dataBodyCase_ == 2) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2,
              (com.google.protobuf.nano.MessageNano) this.dataBody_);
      }
      if (this.dataBodyCase_ == 3) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3,
              (com.google.protobuf.nano.MessageNano) this.dataBody_);
      }
      return size;
    }

    @Override
    public MyMessage mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case MyDateInfo.MyMessage.StudentType:
              case MyDateInfo.MyMessage.WorkerType:
                this.dateType = value;
                break;
            }
            break;
          }
          case 18: {
            if (!(this.dataBodyCase_ == 2)) {
              this.dataBody_ = new MyDateInfo.Student();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.dataBody_);
            this.dataBodyCase_ = 2;
            break;
          }
          case 26: {
            if (!(this.dataBodyCase_ == 3)) {
              this.dataBody_ = new MyDateInfo.Worker();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.dataBody_);
            this.dataBodyCase_ = 3;
            break;
          }
        }
      }
    }

    public static MyMessage parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new MyMessage(), data);
    }

    public static MyMessage parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new MyMessage().mergeFrom(input);
    }
  }

  public static final class Student extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Student[] _emptyArray;
    public static Student[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Student[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 id = 1;
    public int id;

    // optional string name = 2;
    public String name;

    public Student() {
      clear();
    }

    public Student clear() {
      id = 0;
      name = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.id != 0) {
        output.writeInt32(1, this.id);
      }
      if (!this.name.equals("")) {
        output.writeString(2, this.name);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.id != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.id);
      }
      if (!this.name.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.name);
      }
      return size;
    }

    @Override
    public Student mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.id = input.readInt32();
            break;
          }
          case 18: {
            this.name = input.readString();
            break;
          }
        }
      }
    }

    public static Student parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Student(), data);
    }

    public static Student parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Student().mergeFrom(input);
    }
  }

  public static final class Worker extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Worker[] _emptyArray;
    public static Worker[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Worker[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string name = 1;
    public String name;

    // optional int32 age = 2;
    public int age;

    public Worker() {
      clear();
    }

    public Worker clear() {
      name = "";
      age = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.name.equals("")) {
        output.writeString(1, this.name);
      }
      if (this.age != 0) {
        output.writeInt32(2, this.age);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.name.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.name);
      }
      if (this.age != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.age);
      }
      return size;
    }

    @Override
    public Worker mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.name = input.readString();
            break;
          }
          case 16: {
            this.age = input.readInt32();
            break;
          }
        }
      }
    }

    public static Worker parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Worker(), data);
    }

    public static Worker parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Worker().mergeFrom(input);
    }
  }
}
